matchBlocks=spruce_leaves oak_leaves birch_leaves dark_oak_leaves acacia_leaves mangrove_leaves jungle_leaves
method=overlay_random
tiles=0-2
faces=up
biomes= Windswept_Forest Windswept_Hills
layer=cutout
minHeight=75