Black
skins.2=3
biomes.2=DeepFrozenOcean IceSpikes SnowyBeach SnowyPlains SnowyTaiga SnowySlopes FrozenRiver FrozenOcean FrozenPeaks Grove JaggedPeaks 

 Default
skins.3=2 4 5 6 7
weights.3=10 1 10 8 3