matchBlocks=spruce_leaves oak_leaves birch_leaves dark_oak_leaves acacia_leaves mangrove_leaves jungle_leaves sengoku:weeping_willow_leaves
method=overlay_random
tiles=0-4
faces=sides
biomes= Snowy_Taiga Snowy_Plains Grove Snowy_Slopes Jagged_Peaks Frozen_Peaks Snowy_Beach Frozen_River DeepFrozenOcean FrozenOcean sengoku:snowy_dark_forest sengoku:snowy_forest sengoku:spider_lily_field sengoku:hotsprings_snowy
layer=cutout
tintBlock=grass_block
minHeight=55