matchTiles=bushy_spruce_leaves_distance_4
method=fixed
tintIndex=1
tiles=4
layer=cutout
biomes= Snowy_Taiga Snowy_Plains Snowy_Slopes Jagged_Peaks Frozen_Peaks Snowy_Beach Frozen_River DeepFrozenOcean FrozenOcean Grove Stony_Peaks sengoku:snowy_dark_forest sengoku:snowy_forest sengoku:spider_lily_field
minHeight=55