method=fixed
matchTiles=bamboo_singleleaf
tiles=black_heron
biomes=taiga snowy_slopes terralith:siberian_taiga jagged_peaks meadow grove snowy_taiga terralith:snowy_shield snowy_plains snowy_beach frozen_peaks ice_spikes windswept_forest windswept_hills sengoku:snowy_dark_forest sengoku:snowy_forest sengoku:spider_lily_field sengoku:hotsprings_snowy
