particle.portal=90c294
egg.shell.Zombie=FF0000
egg.spots.Zombie=E70000
egg.shell.Allay=FFFFFF
egg.spots.Allay=FFFFFF
egg.shell.Cave_Spider=F5B7B1
egg.spots.Cave_Spider=FFFFFF
egg.shell.Creeper=E7E7E7
egg.spots.Creeper=FFB5B5
egg.shell.Evoker=303030
egg.spots.Evoker=E3A000
egg.shell.Mooshroom=C09E7D
egg.spots.Mooshroom=995F40
egg.shell.Ocelot=C09E7D
egg.spots.Ocelot=51331D
egg.shell.Pig=1B0200
egg.spots.Pig=51331D
egg.shell.Piglin=303030
egg.spots.Piglin=E38600
egg.shell.Piglin_Brute=303030
egg.spots.Piglin_Brute=CB8600
egg.shell.Polar_Bear=ffffff
egg.spots.Polar_Bear=ffffff
egg.shell.Ravager=494949
egg.spots.Ravager=C1C1C1
egg.shell.Salmon=FFFFFF
egg.spots.Salmon=EEE500
egg.shell.Silverfish=F6B201
egg.spots.Silverfish=E70000
egg.shell.Sniffer=FBC1E3
egg.spots.Sniffer=957256
egg.shell.Spider=223B4D
egg.spots.Spider=FADBD8 
egg.shell.Vex=E70000
egg.spots.Vex=FFFFFF
egg.shell.Vindicator=303030
egg.spots.Vindicator=FF5600
egg.shell.Wandering Trader=CB9337
egg.spots.Wandering Trader=957256
egg.shell.Warden=1B0200
egg.spots.Warden=18BFC2
egg.shell.Witch=F9F9F9
egg.spots.Witch=BCBCBC
egg.shell.Pillager=303030
egg.spots.Pillager=995F40
egg.shell.Axolotl=995F40
egg.spots.Axolotl=1B0200
egg.shell.Frog=5A8272
egg.spots.Frog=F17D30
egg.shell.Iron_Golem=757470
egg.spots.Iron_Golem=51A03E
egg.shell.Panda=7E5522
egg.spots.Panda=362E24
egg.shell.Parrot=000000
egg.spots.Parrot=1A1918 
egg.shell.Enderman=000000
egg.spots.Enderman=462219 
egg.shell.Bee=F1C40F
egg.spots.Bee=D35400
egg.shell.Endermite=5A8272
egg.spots.Endermite=1B0200
egg.shell.Slime=F5B7B1
egg.spots.Slime=FA8108 
egg.shell.Zombie_Horse=F5B7B1
egg.spots.Zombie_Horse=170F05 
egg.shell.Magma_Cube=00FFBD 
egg.spots.Magma_Cube=18BFC2
egg.shell.Phantom=425656 
egg.spots.Phantom=000000
egg.shell.Blaze=F81801
egg.spots.Blaze=170F05
egg.shell.Ender_Dragon=FF0000
egg.spots.Ender_Dragon=799C65
egg.shell.Zombified_Piglin=303030
egg.spots.Zombified_Piglin=957256
egg.shell.Guardian=EF6915
egg.spots.Guardian=FFF9EF
egg.shell.Elder_Guardian=6D533D
egg.spots.Elder_Guardian=303030
egg.shell.Tropical_Fish=F9F9F9
egg.spots.Tropical_Fish=FF0000
egg.shell.Zoglin=3bce7d
egg.spots.Zoglin=bdce3b
egg.shell.Hoglin=1e4266
egg.spots.Hoglin=661e38
egg.shell.Wither=FFFFFF
egg.spots.Wither=D35400
fog.nether=1CAC92
fog.end=B28C73
sky.end=FFFFFF
screen.loading=000000
screen.loading.outline=ffffff
screen.loading.bar=000000
screen.loading.progress=ffffff
screen.loading.blend=on
particle.water=ffffff
palette.block.~/colormap/region.png=1 4 5 6 7 12 13 14 15 16 17 19 21 22 24 25 29 33 34 35 37 38 39 40 41 42 43 44 45 46 47 48 49 52 53 54 56 57 58 60 63 64 65 67 68 69 70 71 72 73 74 77 81 82 84 85 86 87 88 91 92 93 94 95 96 97 98 99 100 103 107 108 109 112 113 114 115 116 117 120 121 123 124 125 126 127 128 129 130 131 133 134 135 136 137 139 140 143 145 146 147 148 149 150 151 152 153 155 156 159 170 171 172 173
text.xpbar=EFA8FF
map.grass=60714b
map.sand=A07D51
map.cloth=eaeded
map.tnt=ff731a
map.ice=C8B08F
map.iron=dddddd
map.foliage=495324
map.clay=464738
map.dirt=8a6347
map.stone=464738
map.water=B39E70
map.wood=403221
map.quartz=ECE6CB
map.air=B39E70
map.obsidian=2F3831
map.white=FCEFDC
map.orange=F5BE8F
map.purple=A0888F
map.podzol=8D5A52
map.dirt=7F6D4D

map.gold=E9BA59
map.diamond=859A62
map.lapis=96A4B6
map.emerald=6B9677
map.netherrack=253A3C
map.endstone=495324
map.yellow=CDC091
map.green=B1C091
map.black=323232



