method=fixed
matchTiles=bamboo_stalk
tiles=black_heron
biomes=taiga terralith:siberian_taiga jagged_peaks meadow terralith:snowy_shield windswept_forest windswept_hills frozen_river old_growth_spruce_taiga old_growth_pine_taiga  sengoku:autumnal_bamboo_forest