method=fixed
matchTiles=bamboo_stalk
tiles=snow
biomes=ice_spikes snowy_slopes snowy_plains snowy_beach frozen_peaks grove snowy_taiga frozen_ocean deep_frozen_ocean sengoku:snowy_dark_forest sengoku:snowy_forest sengoku:spider_lily_field sengoku:hotsprings_snowy
