matchTiles=azalea_side
method=fixed
tiles=azalea_side1
biomes=savanna savanna_plateau badlands sparse_jungle old_growth_spruce_taiga mangrove_swamp badlands wooded_badlands warm_ocean sengoku:ginkgo_forest sengoku:autumnal_river sengoku:autumnal_beach sengoku:autumnal_bamboo_forest sengoku:hotsprings_autumnal sengoku:rose_field