matchTiles=moss_block moss_carpet
method=fixed
tiles=moss_block0
biomes=ice_spikes snowy_slopes snowy_plains snowy_beach frozen_peaks grove snowy_taiga terralith:siberian_taiga jagged_peaks terralith:snowy_shield windswept_forest windswept_hills frozen_river frozen_ocean deep_frozen_ocean sengoku:snowy_dark_forest sengoku:snowy_forest sengoku:spider_lily_field sengoku:hotspring_snowy