Baby
name.2=regex:(Obariyon)
skins.2=7

Bear
name.3=regex:(Onikuma)
skins.3=8

Monkey
name.4=regex:(Sarugami)
skins.4=9 10

Wazowski
name.5=regex:(Hitotsume nyudo)
skins.5=11

Cold
skins.6=3
biomes.6=DeepFrozenOcean IceSpikes SnowyBeach SnowyPlains SnowyTaiga SnowySlopes FrozenRiver FrozenOcean FrozenPeaks Grove JaggedPeaks sengoku:snowy_dark_forest sengoku:snowy_forest sengoku:spider_lily_field sengoku:hotsprings_snowy

Dry
skins.7=5
biomes.7=Desert 

Crystal
skins.8=12 13 14 3
biomes.8=sengoku:suisho_caves

Default
skins.9=2 4 6
weights.9=25 25 25