matchBlocks=podzol
method=overlay
tiles=0-16
faces=top
connectBlocks=mycelium
layer=cutout
biomes=Forest Plains Savanna WindsweptSavanna Badlands Desert ErodedBadlands WoodedBadlands FlowerForest SunflowerPlains Jungle SparseJungle BambooJungle Taiga OldGrowthSpruceTaiga OldGrowthPineTaiga OldGrowthBirchForest BirchForest DarkForest WarmOcean River Ocean DeepOcean SavannaPlateau Swamp MangroveSwamp StonyShore Beach
