matchBlocks=spruce_leaves oak_leaves birch_leaves dark_oak_leaves acacia_leaves mangrove_leaves jungle_leaves
method=overlay_random
tiles=0-10
faces=sides
biomes= Ice_Spikes Grove
tintBlock=grass_block
layer=cutout
minHeight=55