matchBlocks=grass_block podzol
method=overlay_random
tiles=1
faces=sides
biomes= IceSpikes SnowyPlains SnowyTaiga SnowySlopes SnowyBeach Grove DeepFrozenOcean FrozenOcean sengoku:snowy_dark_forest sengoku:snowy_forest sengoku:spider_lily_field sengoku:hotsprings_snowy
layer=cutout