matchTiles=grass_block_side_overlay
method=fixed
tiles=2
faces=sides
biomes= IceSpikes SnowyPlains SnowyTaiga SnowySlopes SnowyBeach Grove DeepFrozenOcean FrozenOcean WindsweptForest WindsweptHills sengoku:snowy_dark_forest sengoku:snowy_forest sengoku:spider_lily_field sengoku:hotsprings_snowy
layer=cutout