type=item
matchItems=minecraft:bow
nbt.display.Name=ipattern:*Shinobi Gear*
model.bow_standby=kunai_sword_standby
model.bow_pulling_0=kunai_sword_0
model.bow_pulling_1=kunai_sword_1
model.bow_pulling_2=kunai_sword_2