method=fixed
tiles=dark_cedar_paly_double_door_top_left
matchTiles=sengoku:block/double_door/dark_cedar_paly_double_door_top_left
biomes=warped_forest basalt_deltas soul_sand_valley nether_wastes crimson_forest