
 Cold
skins.3=3
biomes.3=DeepFrozenOcean IceSpikes SnowyBeach SnowyPlains SnowyTaiga SnowySlopes FrozenRiver FrozenOcean FrozenPeaks Grove JaggedPeaks sengoku:snowy_dark_forest sengoku:snowy_forest sengoku:spider_lily_field 

 Dry
skins.4=4
biomes.4=Desert Savanna SavannaPlateau WoodedBadlands WindsweptSavanna Badlands BirchForest OldGrowthBirchForest CrimsonForest WarpedForest NetherWastes BasaltDeltas SoulSandValley sengoku:autumnal_river sengoku:autumnal_beach sengoku:autumnal_bamboo_forest

 Sakura
skins.5=5
biomes.5=CherryGrove TheEnd EndHighlands EndMidlands SmallEndIslands EndBarrens Mushroom_Fields

 Default
skins.6=2
