matchBlocks=coarse_dirt grass_block tuff podzol diorite
method=overlay_random
tiles=0-14
faces=up
biomes= OldGrowthPineTaiga Badlands Eroded_Badlands WarmOcean sengoku:hotsprings_autumnal
layer=cutout
minHeight=64