## CEM configuration for modded Hitotsume Nyudo entity
models.1=1
name.1=regex:(sengoku:hitotsume_nyudo|Hitotsume nyudo)
## Use existing zombie3 CEM variant for Hitotsume Nyudo
model=zombie3.jem
type=zombie
