method=fixed
tiles=lilac_bottom0
matchBlocks=lilac:half=lower
biomes=terralith:skylands_autumn old_growth_birch_forest savanna badlands wooded_badlands sengoku:autumnal_bamboo_forest sengoku:autumnal_river sengoku:autumnal_beach sengoku:ginkgo_forest sengoku:rose_field sengoku:hotsprings_autumnal