matchBlocks=coarse_dirt cobblestone red_sand sand gravel cobbled_deepslate dirt deepslate stone andesite stone_bricks rooted_dirt clay tuff dead_brain_coral_block dead_bubble_coral_block dead_tube_coral_block 
method=overlay
tiles=0-16
faces=top
connectBlocks=grass_block
tintIndex=0
tintBlock=grass_block
layer=cutout