matchBlocks=shroomlight shroomlight_top
method=fixed
tiles=shroomlight0
biomes=incendium:weeping_valley betternether:nether_grasslands betternether:poor_nether_grasslands soul_sand_valley incendium:quartz_flats starmute:quartz_flats starmute:quartz_hills starmute:soul_sand_valley_dense betternether:soul_plain betternether:wart_forest betternether:wart_forest_edge minecraft:nether_wastes minecraft:basalt_deltas minecraft:crimson_forest