method=fixed
matchTiles=dirt_path_side
tiles=dirt_path_side
biomes=snowy_slopes jagged_peaks grove snowy_taiga frozen_river snowy_plains terralith:snowy_shield ice_spikes frozen_peaks snowy_beach desert frozen_ocean deep_frozen_ocean sengoku:snowy_dark_forest sengoku:snowy_forest sengoku:spider_lily_field sengoku:hotsprings_snowy mushroom_fields