method=fixed
matchTiles=dirt_path_side
tiles=dirt_path_light_side
biomes=plains forest savanna cherry_grove meadow flower_forest dark_forest jungle sparse_jungle birch_forest wooded_badlands badlands taiga old_growth_spruce_taiga old_growth_pine_taiga sunflower_plains river windswept_savanna bamboo_jungle sengoku:autumnal_bamboo_forest sengoku:kerria_field sengoku:lily_field sengoku:rose_field sengoku:hotsprings