type=armor
items=minecraft:iron_boots minecraft:diamond_boots minecraft:netherite_boots
texture.iron_layer_1=invisible_2
texture.diamond_layer_1=invisible_2
texture.netherite_layer_1=invisible_2
nbt.display.Name=pattern:Invisible Boots