type=armor
items=minecraft:iron_helmet minecraft:diamond_helmet minecraft:netherite_helmet minecraft:leather_helmet minecraft:chainmail_helmet minecraft:golden_helmet minecraft:turtle_helmet
texture.leather_layer_1=sando
texture.leather_layer_1_overlay=sando
texture.chainmail_layer_1=sando
texture.gold_layer_1=sando
texture.iron_layer_1=sando
texture.diamond_layer_1=sando
texture.netherite_layer_1=sando
texture.turtle_layer_1=sando
nbt.display.Name=pattern:Sando Hat