type=armor
items=minecraft:iron_helmet minecraft:diamond_helmet minecraft:netherite_helmet minecraft:leather_helmet minecraft:chainmail_helmet minecraft:golden_helmet minecraft:turtle_helmet
texture.leather_layer_1=tengai
texture.leather_layer_1_overlay=tengai
texture.chainmail_layer_1=tengai
texture.gold_layer_1=tengai
texture.iron_layer_1=tengai
texture.diamond_layer_1=tengai
texture.netherite_layer_1=tengai
texture.turtle_layer_1=tengai
nbt.display.Name=pattern:Tengai Hat