method=fixed
tiles=azure_bluet
matchTiles=azure_bluet
biomes=terralith:skylands_autumn old_growth_birch_forest sengoku:lily_field savanna sengoku:autumnal_bamboo_forest sengoku:autumnal_river sengoku:autumnal_beach