matchBlocks=spruce_leaves
method=overlay_random
tintBlock=grass_block
tiles=1-3
faces=top
layer=cutout
biomes= Snowy_Taiga Snowy_Plains Snowy_Slopes Jagged_Peaks Frozen_Peaks Snowy_Beach Frozen_River DeepFrozenOcean FrozenOcean Grove sengoku:snowy_dark_forest sengoku:snowy_forest sengoku:spider_lily_field
minHeight=55