
skins.2=2
biomes.2=DeepFrozenOcean IceSpikes SnowyBeach SnowyPlains SnowyTaiga SnowySlopes FrozenRiver FrozenOcean FrozenPeaks Grove JaggedPeaks sengoku:snowy_dark_forest sengoku:snowy_forest sengoku:spider_lily_field sengoku:hotsprings_snowy

Default
skins.3=3