
skins.2=2
biomes.2=Forest Plains Savanna WindsweptSavanna Badlands Desert ErodedBadlands WoodedBadlands FlowerForest SunflowerPlains Jungle SparseJungle BambooJungle Taiga OldGrowthSpruceTaiga OldGrowthPineTaiga OldGrowthBirchForest BirchForest DarkForest WarmOcean River Ocean DeepOcean SavannaPlateau Swamp MangroveSwamp StonyShore Beach

Default
skins.3=3