method=fixed
tiles=lilac_top0
matchBlocks=lilac:half=upper
biomes=terralith:skylands_autumn old_growth_birch_forest savanna badlands wooded_badlands sengoku:autumnal_bamboo_forest sengoku:autumnal_river sengoku:autumnal_beach