method=fixed
matchTiles=bamboo_leaves_block
tiles=orange
biomes=savanna warm_ocean sparse_jungle eroded_badlands badlands old_growth_birch_forest old_growth_spruce_taiga old_growth_pine_taiga windswept_hills sengoku:ginkgo_forest sengoku:autumnal_bamboo_forest
