method=fixed
matchTiles=bamboo_leaves_block
tiles=snow
biomes=snowy_slopes terralith:siberian_taiga jagged_peaks grove snowy_taiga terralith:snowy_shield snowy_plains snowy_beach frozen_peaks ice_spikes windswept_forest frozen_ocean deep_frozen_ocean sengoku:snowy_dark_forest sengoku:snowy_forest sengoku:spider_lily_field sengoku:hotsprings_snowy
