method=fixed
tiles=dark_cedar_paly_triple_door_bottom
matchTiles=sengoku:block/triple_door/dark_cedar_paly_triple_door_bottom
biomes=warped_forest basalt_deltas soul_sand_valley nether_wastes crimson_forest