method=fixed
tiles=dark_cedar_paly_triple_door_bottom_side
matchTiles=sengoku:block/triple_door/dark_cedar_paly_triple_door_bottom_side
biomes=warped_forest basalt_deltas soul_sand_valley nether_wastes crimson_forest